### ISSUE TITLE
Not being able to run it

### ISSUE THREAD

**Issue by 21millions-nostr** [webdev23/Geany-editor-dynamic-color-schemes#1]
Dumb question here but I´m not being able to run the program. I coun not find another way to contact you. Help is really apreciated. Thanks  in advance

**Comment by webdev23** [comment]
Hi . Apologies, looking back it's not clear at all.
Tested now, it still works. 
First it's for Linux only.
You have to install `xdotool` and `php`.

`sudo apt install xdotool`
`sudo apt install php`

The script `dynamic_geany` has some path issues. It works only while being run from the /home folder. (It can be changed in the source).

So, copy `index.php` and `dynamic_geany` in the /home folder.
Set `dynamic_geany` executable with chmod or right click «allow executing»
Then open the terminal and type in `./dynamic_geany`

 The file `filetypes.xml` is the file that is edited in geany.
`xdotool` makes the changes immediately, if it works wells, Geany will show a message `Configuration files reloaded` in the status tab at each change.

However, it produces some nice colors, but it is using the `xml` syntax highlighting and it's not a very good highlighting mode for coding. 
LIkely won't update it, as I am not using it.

**Comment by 21millions-nostr** [comment]
Hi!, thanks for the quick and detailed answer! (and for giving me yet another reason to come back to Linux as my main OS)

I will follow your steps and give it a try, thanks again. I will close this issue if you don't mind.
